// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yveayomkuhvbmczpbcfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ZWF5b21rdWh2Ym1jenBiY2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzAwMTYsImV4cCI6MjA1NzAwNjAxNn0.6FdS2CI8m_6MpomnmK41kiyqXCQf7HvGP2vuEpYqB38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);